configmap:
  name: myhelmapp-configmap-v2
  data:
    message: This is a message from a Spring App configured via ConfigMap!

image:
  repository: if22b041/thesis-demo
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
